services:
  server:
    build: .
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-postgres}
      DB_SSLMODE: ${DB_SSLMODE:-disable}

    #TODO: remove volume later
    volumes:
      - ./audioFiles:/app/audioFiles
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "2.0"
    #      memory: 1G
    #    reservations:
    #      memory: 128M
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 3000:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
